### ISSUE TITLE
Missing (prefix) search results when typotollerance is enabled

### ISSUE THREAD

**Issue by cfranc0** [oramasearch/orama#248]
**Describe the bug**
When typo tollerance is enabled, most prefix results are not returned by the search method.

**To Reproduce**
```js
const db = new Lyra({
  schema: {
    label: "string",
  },
  defaultLanguage: "italian"
})

// Insert all countries (in this case, in Italian)
await db.insert({ label: 'Italia' })

await db.search({ term: 'Fran', tolerance: 2 })
```

**Expected behavior**
In the list of all countries, there are 4 that I would consider to be matching the search term and that are correctly identified when the tolerance is set to `0`:
![image](https://user-images.githubusercontent.com/20073894/212500145-a2788e72-ee68-4d9a-bf26-f4ce0ead68d3.png)
The first being an exact prefix match, the other ones have it in one of the words that compose the names.
When tolerance is set to `2`, as the code says, the search for the same term `fran` yields no results, and neither do `fr` or `fra`. When the c is added, then there is only one result:
![image](https://user-images.githubusercontent.com/20073894/212500270-be452f3f-0225-4b8d-8ba8-83b51b719f9a.png)
And I have to specify down to `frances` in order to even see the other 3 available options:
![image](https://user-images.githubusercontent.com/20073894/212500289-defbeaea-4075-4cf6-ad7e-ecc16358f625.png)

This is quite unfortunate as the added value of typo-tolerance is lost in the missing (from my point of view) near perfect matches.

I would love to be more helpful and provide you with some additional inputs on where to act on the code to have some more organic results, but it seems like there was already a discussion going on about the future direction of the project over at #38.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Firefox
 - Version 108.0.2

**Additional context**
I was so happy to see a couple of Italian guys giving talks about this library, when I sadly don't encounter many "Made in Italy" libraries around, at least in my field.

EDIT: typos 😅

**Comment by lucaong** [comment]
[Shameless plug] pitching in as the Italian author of another popular full-text search library that does prefix and fuzzy search: [MiniSearch](https://github.com/lucaong/minisearch) 🙂 Check it out!

It might well be related to #38 , but this looks like a different issue, since this one involves prefix search results when using typo tolerance.

Honestly, it looks to me that neither prefix search nor fuzzy search are working at all here, and the results you see are just due to the stemmer. The snowball stemmer would perform these transformations:

```
fran -> fran
franc -> franc
francia -> franc
frances -> frances
francese -> frances
francesi -> frances
```

So, searching for `franc` matches `francia` and `frances` matches `francese` and `francesi` because of the stemmer. Neither typo tolerance nor prefix search are working, otherwise `franc` should match `francese` (by prefix), but also `frances` should match `francia` (which is within edit distance 2 from `frances`).
