### ISSUE TITLE
Abnormal memory use

### ISSUE THREAD

**Issue by gtoselli** [oramasearch/orama#348]
Hello everyone,
I am trying _Orama_ to do research on a **dataset of 355000 documents**. 

Each document has the following pattern: 
```
{
   "id":"f550afbe-8a3f-4ec5-9bff-19590869dfd0", // v4 uuid string
   "name":"Foo",  // string
   "surname":"Bar", // string
   "fiscalCode":"NTNPFR53E06B058O", // italian codice fiscale as string
   "season":"2223" // 4 integer as string
}
```
I should do the text search on `nameSurname` and `fiscalCode`, but I need the other fields as filters.

- How much memory should the search database occupy?
- On k8s with the 2000Mi limit (2gb) it would seem not to be enough. Is this normal?

In any case, I like Orama very much, you have done a super job. Thank you!

**Comment by fahminlb33** [comment]
I tried to replicate your scenario and run some benchmark with this code.

```js
import {performance, PerformanceObserver} from "node:perf_hooks"
import {faker} from "@faker-js/faker"
import {create, insertMultiple, search} from "@orama/orama"

const obs = new PerformanceObserver((items) => {
  console.log(items.getEntries());
  performance.clearMarks();
});
obs.observe({ type: 'measure' });

// function to print the used memory
function printUsedMemory() {
  const used = process.memoryUsage().heapUsed / 1024 / 1024;
  console.log(`The script uses approximately ${Math.round(used * 100) / 100} MB`);
}

// create fake data
performance.mark('create_fake_data_start');
const data = Array.from({length: 355000}, () => ({
  id: faker.string.uuid(),
  name: faker.person.firstName(),
  surname: faker.person.lastName(),
  fiscalCode: faker.string.alphanumeric({length: 16, casing: "uppercase"}),
  season: faker.number.int({min: 2010, max: 2020}),
}));
performance.measure('create_fake_data', 'create_fake_data_start');

printUsedMemory();

// create index and add data
performance.mark('create_index_start');
const db = await create({
  schema: {
    id: "string",
    name: "string",
    surname: "string",
    fiscalCode: "string",
    season: "number",
  },
});

await insertMultiple(db, data);
performance.measure('create_index', 'create_index_start')
console.log("Index created");

printUsedMemory();

// search the index
performance.mark('search_start');
const results = await search(db, {
  term: "john",
  properties: "*",
});
performance.measure('search', 'search_start')

console.log(results)
printUsedMemory();
```

The dataset allocates about 88 MB of heap and the `node` process reached ~1GB of RSS memory. After about an hour of indexing, I had to stop the process because it doesn't look like it will finish anytime soon. Based on these results, I think Orama allocates more than 2 GB of memory is quite possible.

Based on this small experiment, I suggest trying other search engine alternative such as Apache Solr or Elasticsearch or even just regular SQL DB like Postgres with full-text search extension. Maybe Orama is not suitable for large dataset yet.

I'll update this comment after I got the timing results.

**Comment by H4ad** [comment]
With https://github.com/oramasearch/orama/pull/434, I took 1,6GB of memory.

**Comment by micheleriva** [comment]
https://github.com/oramasearch/orama/pull/434 seems to fix the issue. Feel free to reopen this if you have any other problem
