### ISSUE TITLE
Can I index documents *without storing them*?

### ISSUE THREAD

**Issue by dhdaines** [oramasearch/orama#408]
Coming from other search libraries in other languages, e.g. Whoosh, Lucene, etc, there is the concept of being able to index text without actually storing it.

If this exists in orama, *where is the documentation*?  It seems that in order to do full-text seach, I have to have *all the text* inside the index.  I don't want to do this, because it takes up a lot of space in memory, on disk, over the network, etc., and I would prefer to store the documents elsewhere and load them lazily/asynchronously, for example.

Does this (rather basic) feature exist?  Can it exist?  Thanks!

**Comment by micheleriva** [comment]
Hi there,
the biggest problem with lazy/async loading in JavaScript is performance with data deserialization and IO.

If you're saving a subtree or any other info to disk and you have to lazy load it, you're getting through a number of deserialization processes (binary -> JSON -> JS Object), which is itself taking longer than performing search in Orama.

Not to mention that there are many JS environments where disk access is not even a thing (mainly browsers), and storing data in local storage is only sometimes a good option. We could store data on Redis or similar server-side approaches, but still, latency can make things pretty hard to be optimized.

This feature does not exist yet, but if you have a particular case study, it might be interesting for us to determine if we want to develop it in the chore of Orama.

**Comment by lucaong** [comment]
@dhdaines indexing without storing is the default in https://github.com/lucaong/minisearch

**Comment by micheleriva** [comment]
Actually, if I understood correctly @dhdaines use case, this works out of the box by default in Orama as well. Might just be badly documented - and I apologize for that.

Orama exposes a `load` API that allows you to lazy-load original documents at any time while keeping the search indexes in-memory (or lazy-loaded as well, not recommended).

```js
import { create, load } from '@orama/orama'

const db = await create({ foo: 'string' }) 

await load(db, {
  index: {}, // the actual search index
  docs: []  // the original documents 
})
```

We will definitely need to write documentation and some blog post about this, as I see the value in that. @dhdaines I'll make sure to share with you these docs as soon as they're ready. I would recommend you join our [Slack Channel](https://orama.to/slack) so we can help you with Orama if needed.

**Comment by micheleriva** [comment]
Update: @ShogunPanda is working on the docs, I am working on a detailed blog post. Will share here as soon as everything is ready.

Thanks again for opening the issue!

**Comment by dhdaines** [comment]
Ah, cool, thank you!

**Comment by ShogunPanda** [comment]
The docs are now updated, see https://docs.oramasearch.com/usage/insert#remote-document-storing.
Does this solve your issue?

**Comment by dhdaines** [comment]
Thank you, I appreciate your attention to this... the solution seems needlessly complicated to me (which is a general feeling I get when looking "under the hood" with orama...) but it is good to know that it's possible and perhaps it is not a common use case for your users...

It's just surprising coming from other search engine libraries where it is a very fundamental part of the system, but oh well.

**Comment by dhdaines** [comment]
But again thank you for the documentation!  I will try it out, you can close the issue...

**Comment by micheleriva** [comment]
Hi @dhdaines

> the solution seems needlessly complicated to me (which is a general feeling I get when looking "under the hood" with orama...)

I get what you're saying, but I should also give my point of view on that: Orama is possibly one of the most straightforward search engine implementations that you can find online. There are beautiful solutions such as Minisearch, Lunr, Fuse.js, etc., and we all share very similar structures and algorithms; there's no way to make a search engine without those.

There are parts of Orama that are more "obscure" than other search engines, and we made them this way to solve some particular issues we have when dealing with very complex problems that some other (not all) search engines won't deal with, such as distributed computing (more to come on that topic). Looking at the source of Solr, Elasticsearch, and Meilisearch it's not simpler than looking at the source of Orama! 🙂

When you say:

> It's just surprising coming from other search engine libraries where it is a very fundamental part of the system, but oh well.

You're right, but I wanted to point out that Orama is trying to differentiate itself from other search libraries with some features that will be unique to our solution. If that is a dealbreaker, Minisearch is a fantastic library, and you have its author @lucaong who already entered the thread here, and I'm sure he's ready to support you.

I'm writing this because the feedback you gave us is essential. If we see that people are accessing this issue more often, this will be a part of Orama that we definitely have to enhance and prioritize. But I also wanted to give a bit more context to what, in our vision, will make Orama different from other JavaScript search libraries. Not better, I'm saying different.
