### ISSUE TITLE
Investigate options for reducing some kB

### ISSUE THREAD

**Issue by benmccann** [oramasearch/orama#418]
**Is your feature request related to a problem? Please describe.**
We're considering switching from flexsearch to Orama. One objection that was raised is that the Orama library is larger

**Describe the solution you'd like**
One potential way to make Orama a bit larger would be to load some of the functionality as plugins. E.g. instead of specifying the `facets` option directly, the user could important and instantiate the facet plugin with those option and pass it to Orama. That would mean that the users who don't use faceting no longer have to load that code.

**Describe alternatives you've considered**
Rather than a plugin, Orama could dynamically import things like the facet code once it detects it will be necessary. However, this would likely result in performance that would not be as good as today's because a network call would then have to be issued to load that functionality. If the user is responsible for loading it instead of Orama then user can keep it as a static import so that the required code will be included with the user's bundle.

**Additional context**
https://github.com/sveltejs/kit/issues/8712#issuecomment-1587661316

**Comment by micheleriva** [comment]
Hi @benmccann!

What exactly do you mean by "Orama library is larger"? Are you referring to the Orama bundle size, in-memory footprint, or something else?

If you're referring to bundle size, it is easily tree-shakeable, and while the full bundle is about [20kb gziped](https://bundlejs.com/?q=%40orama%2Forama), you can create a static search index at build time and import just the `search` function, which is about [11kb gziped](https://bundlejs.com/?q=%40orama%2Forama&treeshake=%5B%7B+search+%7D%5D).

While doing this test I also noticed some points where we could easily alleviate the overall bundle size (i.e., we're still in the process of moving all the default stop words out of the main package in favor of a separate `@orama/stop-words` npm package). This will shrink the bundle size even more (saving about [6kb, gziped](https://bundlejs.com/?share=KYDwDg9gTgLgBAYwgOwM71cOBeOBtAKDjgHIIEALEgGiNIBNgYa6SBDGZ24kgSxZ7BkA0gCs2AcxEkKKaaggBbaRTbDupMAFPpjda0XB60gG5so83lI0kAZgDeLN1DpsxeAGw-SAJ04NC0kxcrEoqbIy6wNJsJtK8CADW0TaKVroAripCyCms9K6sqLz6PMhZNqr%2BPCUweTyqaCooYc6JGV71pBQ5wKi6ftJppaSKakGiprzGNu3IkTbIWhIQITy2UFojJBlrpMiDNsC2ddWkGWBgU1HKNmZQbKYR0vYmwGckPtv06bPjziVHpVDqxVENVjEvEDWBl5u9pEsVttgJ0PmwvHsSIoAJ5JJjyIz-ViiCr5HLQnioUQ%2BDxxGyMTgU0haTG7Ik8e68TEUDIfEoSQKpLmY5D8GwAIw8YtYkuAdNCqH69JKUUVTJIiIeUQeSplUo%2Bw3VqDYijGUw8yWRHxc9HZpBMWg%2Bkt4Ji5qt1NWQrQCUO2NrUmPuDg%2B91EXRIrot6p%2BnFMwFurEjyUxxUZ8i0tuQ6vumJ%2BWaeUA99sdgcd6vemPe2c8iTYuoAugQCKBILBECh0HAoBkcPhWIAOEGkgCYQYeAPhBpIBeEEArCDSQDiIIAhEHHNlHE8ngAYQaSAeRBpIBBEF3S9YgC4QNeH6QbmyL4c7mfLifn1jzk-SKeAZhADzwJ%2B-SIAWEHvPHngDSINIp42IAwiDSIAbCA3qwQ5ATYgDsIH%2BpCAIwgcGsIA-CBfiQi6ANwggAyIIeWFTtBPCADwg07SKhOFYUOo7ztIdHSKRU4TtuNhToAkiAkaQ070cu0j9vBz6keBF5TuhU6AAIgeHAaOL6-tIv5QZOokwd%2BkmgS%2B0g4YO7E7jp0igcpNj9gZNgTrprCofOMk2FRk6vlh340Wue7mf2yGgd%2BtmsKO6GbjZhkQcOa6kbux6IThw5Tt50iPmFNiYYuCWsNeyFsawFmzo5z6AJwgTGjlBfG%2BRZcWgcVPDydxJBTjugXmWuzkOflNjfjhGVkWh-5TulAmAKIgc5TilPBUUhJA7qFc6LshlFTkJdleZeNjZdRQ5TiBrDZW%2B0iSWu80PoV1VpdVmHfpBgkTj5I1eVOFWkMFF5yQpNiHktrCALIgi53SQb60ZJplxXJWFJaOInSJ9QPASeo4talo5Dtew08f2SMkPB361VdpAQ6jo7fv2q6JaOC6WWRMNxUNU2jqhDnVceRU7h1pDXrls6uZRAFmUeXljYh2WozuEVrvVMHXgN7mEfJY3Xm%2B36sQVEGftI6H-euhHToAYiCKUOY3U4pGlvrDPB9XRWMkJh%2BnVXeZ12aO%2BGABIg1VfYNklzeD86kzx7OJZJNEy1hFni0eJ5rkzJDkZDNi7fBa3hXta44WN86qzYn2qWTYdDirxOUzYJu%2B-bWE7rRgByIO75OJVJMUCZ%2BUvaaBs6O3O5Vm8lDn4fBYePoRRukCjlF28RV6vs9R4rlOs5KzYCNlzYzEQd%2BqmNs24DQPASBoPAYDwLghA8AsrDqhA0gAI4ZOG4b0Mf9LlgmPAZHfmjmOqSCPxqADH18wmaNgQEWGpf0pOGfMNhWxDDYLwf%2BdZdB-2kK-QBoxoE2DYAgkgKJL5INYAAA4JKSSkGQj54NIGfNQV8hgZC5Kgr0-9RAAEOghEJIDAE04oACXb9UAAGfpBgBRKg3hHh1QcFYfERUqCUTlmQDAKAl9gCQEgQSN%2BhhUCKFQSg-%2BmAMj-zPvGBEmCeCGCCIqC%2BHg%2BimHIAAK6McaBED8ES6OcAQ-%2BhhGFYOcSUMEiwH7qgEbAo4gjtEEO8IsTh-8PA9CiKY-%2BfRjTROMf-AR%2BjSB9DqJE8MMBGGpLuJY-%2BJg-GsHCWY1IwAtFDA8UkphJTpAZPVHUUpbgnEIj-goJpapWkKH-tQ2JkTowSLicwoxdR%2BkVLYDo0xMQxlCLGUUw%2Bkz-6QJgGos%2BnhxHoAgIwlJ9CjjoBNPkwQ6BP6DJdBfdAcoTnuDeKo-pxyHhvxSbEcs6BaFmCuYMh5dz0A3MeRc1hty9nJNOeIQZwBxCvO2XUUFRy3jGKhaw4xYLWApOOfCqF8JwU3IRfsi57wHGgmANKBoWzQSxHjP8mQhzKjrLeM0DIlyyWyFpVWN%2BDK3hakpbS35uz-6qCBZUNgoL6X8pNDS6FmARVwswJi7oVKYm4oaDKj4LL3hSpkAquV0rGUyIJRq1lRL5WatJdyhVFLQQKt4OqJVUAAC3XKRXvHNRw9Z8glBktQCawQbLWCcpVUy6QtgKF%2BogNquwLr-62GgMKmw4bPXrAAC9-I0SCo0SaVWYEhVG5p4ZbCxvhWS8NKKM0fGjSq6N6qSCYC1QSKAerSAVsNVW91tb7XJutba5wza351GQLIapZa6gqpgOw6p5TqlWu7W21g7hx2duOb26lbhjkDq%2BTO1ltSXTerJV2zxk6hCqAHbuyNk7kVioXSYCV9bT2ypXWio9rKl2sr7Ti4Npwa2VJkfuqAja33mt7a2j9DqWDLxbGvdsm84Bel7HvUgEBrCsGDWGWD%2B98TIMrMiXMgoj3BMRdab0PBtBRCGEYcI2xYjxESMkMjiQwzanTAWQjiGm0MaxBhwQsY%2BUfFw-aYNwwylseJeEegB8GiwgRIUHgEBWW6GzERqNMaGCMN2JYb4ZbmnSAgJccB2xazbEaNyvJHwUSmMVWYeQtYsNANpPIUQAAP8z3Qb08HROMu4nhpDOjc85vU%2BKPPCmkHMXI8RkDbCWCGAAZzIvznGAEsf2BAcMkZPNIYi84KLjAZH-zmNIXliLOAOf2DJoo7ROhRCC1m6AUQmPFCU%2BGVMmJVGYjE6MYAApuT6ejVEXLuhIEnphF2lQ%2BnMyBYFN8FUyo%2BM8GdNaE0hjKhJhizIOb6YguBdFIRrwUWHTGbywtst%2Bm9MKIlBmcM4pzAX2W4Wn4frrMGjUAKNTEgXDyClIkUw4XAzheO1oY7zW7sAj0LobE5GAfkfMFEYNjBeByZIBD9LYO36XfpI1tBTH8XIjdEcXz-ionNC9My0QSOe2UvDD0Ur2Qgug8qL0I1ipmjGO2Lwcj1GbD8mDSUKj4ZEjQFMQd1gnPCyoMSCZ2Y9w-P3B6B4dAov5uC%2BDTL9rxTCODaFGUgLqRAdM9YF6JpnPgsQFrNr8riw9dUL18loowbihGmmHactqCFCKBTEoGb39pAXCuHcHF5izccgrPFteBYsmJnMCEIDq82wb07MgDwkGyRBG2GYenL23AYNzLwcMo3EXzYoLwSYlORRp8xAALxz-T-%2BAB3Cp6mYg28MJidEuSICG%2BJTMbD4CKehGZWWpXrBC9Ot-rYaQFe6sl8IyNovqCr5N-E5JmwhfwzF8oG5nPam9fVIhDYDXBjl82Aoehj4tp28NDYIf-Yx-FXAHFM0YnwBjjcgv%2BKebjA5%2Bu8HwGJpTHC-okI9IYvufNeMN%2B1YAFHmyUFtExAL3L2gH%2BzcHICoGQTsxIArxkXjxvwQMMG2yvnm0WXm1UWQxlHm17zhA%2BG0xUBE3pHqUPk6H-hQDSyy3LCEG5TTw%2BDLzT0H3eBb0cw8HcFEA4IYFgMHygMxDL2ADny01hFyG2A7B-xRAH2T2Gz0WkBkSMHL1c1mDkEWAgNdzL3iHjFIWkAFGEJSRiCILyFD1bHXg7HgC5Bj0c14PYAQKczUWDUkClEhAcIkAcKhDcPDA3jgQgAQKQHB2jC-xvnWykyCI8KCK8Ckw8Kky8NCMSwYHBxREiQ8An283pGa1cMyOiMyNiJyMEVSPT2CxSMWEMyoQyM1yyODVyFyKqPyKqPiMaMSPLUYVQA6HkA6DSM6ItwyEiM6LqPwQaPwSaJGJaN4Q%2BGkRfhQGkVQV4FQQyWkA8ADRsG5yaWDTyWDTSKgFQTSF2J-SFEqK33SQyAWIIWqVOOfXPk6Lt3OMcSDU6OAT-lmNaSmNeKgBqOeO93tC%2BNQTyXQCh3%2BOkQ2K%2BPDDSGHTgQ2K2NQUKNWK2PDH6LKPiAQLIJhC1x3xAQMHLDsJ6zw3eEoBEWQWQEoB8KUEvgkxgXnVYBJLgWzzgRWM13UNYDAF4AAE-T4glwwSEpFUFuT3AOSAx1Q%2BSuTz4wibAxlsjWAJShTRSWidE1kOSkVFSdllTA9KQrjOAzjOBnC4Egh4gli1Nmhwhg1t1HNxRxQHU1E3g1Tug1B0TD5zSDiHSLSOBww2BHS1ArSoAAAnmIEwB4Zw-0nBZBf00lP0mRG09gf0u0r0o40gWIdLfkkMmRc0t00M00WM05cM%2B-d4K0uUPM10P0uUIRN4F5As10oshPcRR0osz5IIVMosjM2syMnMnY2sqrEM2Vds3gVRds3Mos%2BYK03YIcgZEM3YQM3YGrFoAkYNAAC8sF2UsCYBqydPVIrIBE9PkHMF9OcGfgt3MGDKKFO17N3IjJq2fiCzt1O33MTJvJzK3PfRPKPMTPPJTIfzbKOA-Ow2DSrCCAeDLL-IeRbIeHtPWAZPWGeODX9T9QfifIgqzKjV5GnIzUVCgszUDVQrgtIHzQrVWUwEHL9TYAQAQHmMIqgqIpIsXKjRjMIuItXOwoovNUjNsEYs3Oop9MIoDM4sPPWGPNQRYrPM4povYrjLsFOzrJEobJEqbJEoQtYAEtbP4qIvzNorlHIoQGLNUoAuoo0rMGYuUqrL9WABItUokvkuMqzWUpkvkuUrkvWAsq-N4o0tQtMtxIYucuKCwrEo8v7J0qEDIWcEWXkGYQt1HKKHcCovCuEvCvovLQisjM%2BTYqio4sCr3OCoPPSvfTt2YUEtSpAtAtrRytEp2VvMyvvLyvjC8pKpSRqyKtTMcsKtiGytiFCoeXSu0qir0tqoeQKriuCFCqVMCuCFqsquypquCuGoar6pcqGphVms8rGuMSmp2QItoDMJAwj3gA2BsPjMYTYAyBACLIQDgR8JmX3jUH-iEwYDOvkyCGKyODQwYUOuZwQM31IFhIKXDFMV5CWPAsQXAR5wMTBIsWdyBucQeNSCZLKCeM6VWG%2BIAQoPE0kMYTABPxIFRoSXWQ%2BDPkVI5P3IJAJA0ShtrR%2BrcFqXSRuqYQhsnWJqYQU22FhD9wb2kT90RtIGOvpCywNJsB4tGARHkGqWkGxGkGkFYUHVFsHXDDFtYUpulv-jFrf0cUBoBUGWdVNEposSGWdSkSrQgV1sTSh1wqaHbRkULyrRmN1uVvLSrHRyKHtSkJNrTzNpNogSEExAVqto9vdvcAdq9XcBEIltdp1sQrDUUyjQAG-lE-Vw6tbELkDHcraFBbbKQIBsRfaU7sQA6Us09g75KtE3K7B87KbbAY6YLUL07sL86nay78K69sRFbEUNlrijhz5ok2b2BnCoE8ljbD43hnbQhc7HNeQ9bkFh6oFh6YgkKe6h7TbJ6djB7dqAzx6Ay69eR5jp7F7q7R6Ay3a-SIEu6IE69XQK6oyt7e6g7Kww7EVI7KbgAY7b7eRd7kFWDn7KbD6Yg06N72BM7%2B7HMc7L65rG74kghS6W7y6v6SlUKs6gHa6TqTKbANKPqeBEHeaSANLMR0HIyEhWcJcljKbvrCxFSECxlAlDMRSyGNELrnVpR1rw9LC4BbBeAdqyBRjoNTFJDTFMRab-DKrwweHOtf49K1MWj-Dg1RGOzQgpRUxhHIEM9xMpGezQa2HZGBHJHZGhHf4pQuGpQOHFG%2BGtHIzRGNHJHljtHTE8DBBHqMcgh1aghVHBAXQfBh8DgVdUSt9yhnG7iDASh871RhgtEwr3GMg3HRgfHWGsQwnAnQnyh7rzcXGARyg-QfGUwfGrdyg2kEmAm0ngmkmYmkHa1InsnYmGgvgVAvgs9ynuQvgYAfAynchFRangR6mam6mb8dNymvBGnQQOmWmmmyHv9ilphSnBn6AnHCMuQumgbutJmmsFkZnmNeBs9thDBPAPB5mVmuD1n8VinSBIy6ghnth9nRnMR9nemd1pne05nLmlnLnOnbmzmeB9mdmZBr8Dnsghm78Jn3mGnvmHn7NFm5H-m7nKdPA-mXnVn0kfBFB5manoXDmnGYWfAfm3AkWwWamKBhnJ0aQ1nqkaQ0XsXIX4msXEgJHHnTiLjaaMlVhalTiMnJ1aWom6aIBZBDnTjwmqWuCaX-CWiqXMSyW9dSWm0CQkmwXigSh5mxXRXeBFn5tihgXzdNnLBnnigiX1SSWaioX5mDhph5ttWwXtXkXNcfArnFhjWbnTXVmtXjXFWLXnntXVX9hjX1XbETcdXdcuR1QvRutPWg0VSjcAX3XwmvXOX1i7Wg0%2BXYsGdBWNRgFpXoDNdpX9XpXDWyhk2k2A2ERpX5XU3QWtWs2WjRRxXM2o3ZcMh9dZghBpdK3MRkx5nLQYk63K30BG3cgq3aicWK3aiwX63nn62HWSB63nWK2YBEhG23W-MmBR2J2vmK2LnZ3m3p3zXedtmO3l3c3p3e3Ucx2h3vGp2hRkA93vGD31mZ3vGU3QmF2hQl2t9s3QmbXvHnnhgT2d2t8R35nRA9d1QP2D2v3qWstmlf2-XiRmXaaP3wmwPGWwOWjv3f2X2xBVhy3gPx2N8g1IPfWbEUOFlf2M3MPwOg0Q3cPoPw3sO4O0FOB33APItUBEOeB2hAWsRdhGXC2-RgBD31Tb2mER6g8bczANiIEQc-MLqMODAy3j93Xth5FyNg1sRJTaOQmNRpXgtsRwCYAetaGLCwM%2BhmGrqSB8mSAdE7q48haYgliyVGAECC6AkeEp9zgJPn4-DddXcI3WjIRTO-CvLFBaEElfKih26Wj67DTwUasrVrOoADPwVJEWb6TSFdiMhhaEnnVxR4bmFFALTWFlnic6xGXVB4v8gaCRSc7VQdPFkArGTLrh6pF0kIAr5-5YQYTKbVsEGZioc4ayU%2BgTk1FKu7q0jolBldiQuiTY7KCJA6vAlCS0SyU061MXjf4pjqC3ibBWEEDmEeSjFvkyVFAMhKBeSKEm29FbRyFtv-4EAglrOkBuvvk0b7koEPARuswbuVhWlWv3Eyl-4YAAAv3tCEhpC46JKEWGhQOb8xQHnYhvEHyvZxK1frvxqHyHipDJKbhpALpHzdOLipdoxH3z5HrH11NHzpVumb--FJKHcoYnslUngEipEwAnqa6n4n7MGnslOnynuJNr7pcFVOwZLzrnt5H1J5K2zZZEdAcbrFOFYFPnwdAX4XoXnKkXgFHK7niL6tN5LK4ZKAVhKXhXmX8wG1FXm1NXm1CXnX-evXm3e5E7N5E7fpWhE7I3k7TX90s39ARlQZWlBZc5WlVZDJV0CXt305TXt33MmXwPqHFJEPipMP10DdfpcPgP10KsYP%2BPguyPtPTAGPqPyVNn731P-FdPnP7X1axFHZUrrFCIS7mrt5W0YZOwiJPlblC1C9YlNhK2xocIbHo-eu%2Bv%2BulVHL2hFvtgeunTd09X8IJLxXpv5XvlJLxvo-JLjX%2BvsfofpL3Xqf1tBfv9QVZfk31fm1Jflfpv-X0fw3zfm1fv8UXf0gh-S-93y-1BHkC0nvjIC0-37lJ-pg2m%2B-pgi1N-qsV-tLhNa-jbT-5f8dMP-Aup-3a7AC4UM-boGANz6AD8Ko-HOiX1tIWkUBMgd0tbiQEV8p%2B1uImrlw9S30iaqaX1trQJDJp0ewACdEAj76JobcFaOXtbWrQG1X0daVNO8Hn5VpaELHVtFWkP4m1j%2BBtU-kILN6h8dQotAAZ%2BW37YYbc-qKChQjsqV0s0FCEtAoP2ah0g%2BMFX8ohV-4wVo%2BWgpegYNkGt1lBkAvQZnw0GYAra-qdrkk38p25pgCxIQI9wXR7dXBquHdLkH3TIBOB7grAs4PJrIAJA8PAId4IkC0De0QQm3F2noAj9k88wZgZENiGvoYhqvJIerytqpDuB6Q-fo838pr8ch1A3ZvkOEGFDDmQgXIcUOQD8DPBggyIaUPiEX8GkVJMlq6EUF008kFxH3qjzaHqCuh7-VlvHyhzZ9dBzQ3gPoLGFAD%2BhCfaYQXRGFp9%2Bh0AgdIHysFvcVh-g0UPYMiGODthB3eIY4Le5CA8BkQgrOp1AydghAzDbjGCQIGjBsQmADwLIVYDCFXc1BUmqEF5BvDCwKIaFCwFYBp1GEAIj4ECP-ggiZCQtLGg8N%2BG0A8UKgHsnCMYKKAHhTwooLXzxTn5CGlOb4Y8PiAqd5kqncETCMeY9BbhTCHoJ2h6CQ5qklIzEZOnJFQiZkzw1QEIWzyL4bAZeQnEyKiwwBs8b3ZkdSPa7Ui-4eQQ%2BG-CtqnZX85eT3BKG%2BzzYH8-IP4UfhaG2l6%2BNfFqkEMVF8EYElNH4HYSvgKiiRpAFgoMSNHrIPALeVEU5nkAMpzRcCG3EgA6AWiDEA-MpBIAoB1YAmamPou6M1EAAifgIoF9EaBfRAIkgDIiDF0BfRESVABGOIC%2BjUA0Y2MXAH9HMAYxwYl4eGODE8jgAwtTMZGP4BvAkxIYp1IWPTHRBSxkY7McLQrFxj%2BA9AIsaGPrHBiIkTYyMQmOiCti4xLwzscmKrHQ4ix-ALwA2KdRDjmx0QUcW2IiQTiux44jwEWL7ETj8xqAYQDACLGnYVxRYivMuKYSbicUG45sXWH3GRjVAbwI8XGNUD0AzxyYzAtuNXHBir4V430bqKPGRiy8cgO8a%2BLNGXidxwYhMeMA-FxiExX4x8QgH-FJi0GMZPYL6IdHmjHxm3dAC%2BLjGcNy084-kWmNfE9p0JXYtCUWJ6ARYsJvYvCdEAIm%2BiORgQEiWRPwmbiKAwtEibIG0LoTD4hzNEUxLsLigr6NQJ4eJidDGV9qBdCpLCHcAIEORngEUeJi4nxlMQ4oUkfLmeFcg4CDpdZHXmCElBJcMomAIYXpyrc3AFAHYt6MyAfENRMo0tDEBODbZ3SEmb7GkW0IwE-UOxN%2BBcBgRl4tJXorhpIVsASSyAM%2BNErQUNHsAVJ2wf1LADwkCjJCxJMSfZmS5ETB8JOGKdKKZGkj6Jmo%2Bwg4WQCkjxQqwBSYICIpZTsKwAGyQYGgBglni03EKSliUatE2RTYMoCbg%2BBeg3JHgUkRAGclbkKpLSHSdEMbxxgoAuXM4ZtTgD0BEgzDGDPqQ3zNYOsMQVDCVmHQIFts9uHhEjh06GA1RJGTybJJqDkZZEIYNGmkEqy-AAgVjYlBxjfiFl924QEwDpz3SkFgsjCSyfvnVAbBowCmHEvR0YBvwyUVeVIDbl0z9YbOaCVEP1meBtAQidtSzFiO8LmgPMcoPzOIWKJ2EQsr2eGlfCYxegWs5oIjtqFvpmS6pBWSkEVhaJ6APBljPUcNV4z3ZHsGJXycSmVHQ59pjmOEDpn8pgkSgbpLgvRgsYFMUmRMn4gaGq5dZAGDQNoV1l1weFicZKZ0DTLGBBC3SbEqUN5IaBMzckH2E5nSTGnWgMwRIPqfQ0YDMN3S5k55k5jLSGySMAM%2BAtjngI3d2poo4wsYSpn0y0sbpEwm-FIR7jbZOKNECYSgREFnZRBEjEQQ9lpZx6VUoep5L4luZRKFpbYM-yXxqT8gwRNILmDtI0ZMiymS6l3hfpxzLqbAAAPvagHhV-TItiIfzKY0AKIYue6DLmP54w%2Bcx-Dnw8AFz8gdc8uTfGMT1yMEheRhBDmUwsywcXg3uVXJZn75UcOonIJjKHl04uswcpIvvk7mp8usgo5UO13hz5955FaVeTqP4L0h-c5BKAFPLQT0dh5QQFmXchZlo5cgBmFmdEhKB0zkk18wAg41FACgT5j8%2BbKjisDbY35AoK%2BcgDGCzS%2BQFAenBQA%2BR2MtxDCD%2BY-QYTvpIFr8x%2BgZkfphoAAPx8AFDyEbABhWwaP1H6Zdm5xKbkBwEjLMi%2BslQJgnCJ0y1BtsCQXKREz3lpB-5dC9PLpLLSLNkC8QRhfQrbp7z4RzOLSW9MCzzJY5PAMMDpyEVloRF2wERR8BEU0JK2WWStm-DDASFZF58pRZTTDAwBC8NbJObOy0yHztFZaZIKfOnbKK9FGWewKVi0xmKuuX0kkssxrxqAaSX04kuSM0w2KXFZUrEk4sporMMuPcwZn3L8U4Fh5BoYee4g9E05Ug%2BdSMlmD3mihKA%2BeOJbDRiXydygHGS-L-DtnQYAFNWYALpJnIsdfFdtY%2BXktlZBLiliaeuQIoKZ7zigDCxRQkxxJ25-CDiooE0ucUpYPAri9pSSRwwdKegRNE0bbgxBTlfZ2tSpSQAQXvlXcDk%2BYE51q6lzZlZaWEIgIxJryVllNQSdtnj4IE8kJ02mvpkHw%2BBGFMy9kWjSQLzYkCYy0BeyPGnXLVCzw-FKcDYK9LwwwhZ5W-FeWdL7lzy5giiBJJSjzs9yqADp2EJArzlGcngCwSMDbZjRwkqkeyMhx2EWChYIQqgjfGdBtgaKrgi8qQXAqcVBBRhB3LfgdyPgheJAj-hYKoBPl9YIAA)). If that is a priority for you, we can move forward as soon as possible (even tomorrow).

Talking about functionalities such as `facets` (I'm taking this as an example since you mentioned), the `getFacets` method is about [<600bytes gziped](https://bundlejs.com/?share=KYDwDg9gTgLgBAQwM4E8B2BjOAzArpmASwjTgHNgYAxBDSpAHgGU5QZg0ATJOJjAC2ABbBAD4AFACg4caAhEAuOAHko8hAwDevAcIRKWAX1EAaaXCjAkuADYwkSgCoQA1hz7RgAbQC6Zmdi09ADCJNiEZEo0dPYACghqQkhmAJRKsVAQQoRIwAzRlABKVrYwonCa5hgkSPCBMQ5wBTDF1nZwALwVhlU18Ag2NgCSACI8XZZt9gB0ImDi4l6EnD4pneXLKb1otYiDIxAY44gA7giE8HIi05yHuEIc9kwwntMUMACypYRgNsDiVwQNwQMCBtyOJj2wzGWxk1R2dSCMAA0sAUMdlAAjABWwAwMGmbnR4nqITCEQAhFttrswJkwMBYIQrJ1TudLokgYQuKA3pQmMAEgIEJi-hkIAymVYAOoXfiOFAMpAAznA0HTbmcUDUgLQODieG7UmXbA4JGo9FrSoyGR-eAANwGuBZXU0PXMMgA9J64AAJWguOAvci4BIINDsYBBwRwJDyKPQLVQWSmtRoCg8ZCxhkYQjhYCcOCYlDRqO4XJQD1wb1wRzKEbKJTFe05C7RnKyTBR6pCSBoR48GzhzhVvP6ukSxlEKxeY0%2BTodLoAcjQ90xjKXVqrcL6FQs4YzcEMrONSFCaHCZFnSPnWYAcmvGc0RsBwmgLsQ0Nu4Ib4DBe6yvjftgeoGruaYUCm%2B7plYW42vBQa9tMYDlvwiwAAYACSaBBwDTNgmRCIYAC02G4dMLyGOhkIAAyrN%2BPQIXAjo2M6GI4niBIEVkACiEZQMyyr-mAsI2u68GnteMTzq637VPgMBKDR-gISxbEqTIjFHpINL9PshxIAAMhwZAwPwrIDDYBxHNMfzpmZ5ggcm4h2nAhCsjRADcblwAwULWUZJlmd5hAANShXBNq-nA4IWfpRxLD4OkSaB0XGlBxoWkgkXwWlSIAGpOlGXTGhqmCsVqypLtMm7fjIAD8%2BoIGcbbvHeVjsJwDC1AJ6YSOCFKQsaKQpBSdVwEo4gDVJlC3jwApCvwIp-IVrHADqCHRROkowCgCoMqy21ToJM0wElTFICcFwCOO9JTntirrRU40YMgUYro%2BUBLko1pMVF4EHi6%2Bqnuel6nXNcAPkI65QM%2Br7ch%2BJApNMuFIONcIDBgtggsAUMw804io0NSJIOD0xqVYxMxKtzqIDwq7Q4yol-UWlgIC441aUxr25HAH2M1Avjfc9LM7giexs5wKBDDsU4FjTQP9icvCUN1MC9WQEjM390Wo6yJIk6DETg3TkOfXDb6I2gyOo%2BjOCpbu9oZQVRWmwAglAagoAwDMw6IOWi69NhY0O7B40%2BSKE4DyRmg0ZMUzH9qQgMkvS7LsDy0V2V21zf2YmzHMs7nuVvXzmIQBAfzht9L2l0uPXcmQwu-SzQchzjABCFdV2gqjPBrBOSXO5NZ1TlAK6bDfpnAAA%2BRbd4KaCQkdsAPQy2tMfngqF39xdRXX5eV4vQsKLXvP1%2BrjcnyLge7ingpSzLFadQrxxKyrMBqxrWt29F3L9lAfaxU4Ar12kAhcy5D49yFnARqS4oGLyXBNPmU8m52ycvqaKTsICmmNBPLMHsvZf0brPeeR9wz%2BxvqLH8mNsbsC7uQ3uUB%2B6N0HiTeOo9mKQn-oyIBycbCpyfnLTgr8N4IT3vBLe7NOYMSrFpcS9tnJ5RiM7GIWUA41lCApUscBfaMiggnRRrBaDmWNFWIeN5pjyQjKyLEuJ8SEjRMqCx0kR5rWyrZIK-Bko2hrEwaAlw0A2BLKg4imI3qFlPKOU04hQEnTnBAlBl90ybiof9cWqCLYIyICQE8htyRkFNiw9MWT3w5K-MBdhw9DFdDsZxfChE%2BKXysFIFmdSHGPAEi0lxs03FsTEfBaYSAAkLAQJCTEawOjlGGUydMGQCyEFeuwcQmSkQvktuUoZATk7jJGnbIZNhFn-FWTEdZ2TPzTBwdgXI8B6qNWUrGZJZBSlW1soQbItzGoAEYaIpA0jabW8ifGWBgLgKApAomGCAA), so I fear moving this as a separate plugin would not solve the main problems you're describing.

Even though I see some value in being able to call some internal functions on-demand, and if we find a good way to do it without compromising the developer experience, I'm all in for that.

Let me know what you think! It's useless to say that we'd love to support you with search, and we're available for helping and providing development efforts if needed 🙂

**Comment by benmccann** [comment]
Thanks! Yeah, I was referring to bundle size. I was just using facets as an example, but it's not necessarily a priority of any sort.

Moving out the stop words into a separate package could be interesting. That also makes me wonder if there's some sort of client and backend separation that could be useful. E.g. we could create our search index at build time and then just ship the index and client to the browser. That would allow users to use the stop words still for indexing without having to ship them to the browser. I don't know if pre-constructing the index like this would save size or if the constructed index would end up taking up more space than the content file we're constructing it from thus actually increasing the size of what needs to be sent to the browser. Anyway, this client/backend separation idea is just brainstorming and not a particular need of ours. I do think it'd probably be fine for us to use the library without stop words given the types of queries I imagine we receive.

**Comment by micheleriva** [comment]
That's the strategy adopted by our [Docusaurus Plugin](https://github.com/oramasearch/orama/tree/main/packages/plugin-docusaurus). We construct the index at build-time, compress it, and ship it to the client. The client then will just import the `search` function (which, without stopwords should be around `5kb`) and it's done.

Of course, it depends on how big the index is. But for the average documentation website (and if I think of Fastify, it is huge), it's working fine! You can test it here (as soon as the search box appears in the top-right corner, it means the search index has been downloaded and it's ready for query): https://fastify.github.io/website-next/.

I'll prepare a release for tomorrow by extracting the stop-words into a separate package, so you can test it and let me know if there's something else you'd like to explore.

I'll update you asap!

**Comment by micheleriva** [comment]
Hey @benmccann!
We just published Orama v1.0.7 and went from `20kb` to [13kb gziped](https://bundlejs.com/?q=%40orama%2Forama). If you import the `search` function only, it will cost around [4.88kb gziped](https://bundlejs.com/?q=%40orama%2Forama&treeshake=%5B%7B+search+%7D%5D) (it was around `11kb` yesterday).

Let me know if that unlocks your use case and if we can support in any other way!

**Comment by benmccann** [comment]
Wow, that's great! Thank you so much!
