### ISSUE TITLE
Question: Best way to return all documents

### ISSUE THREAD

**Issue by ghostdevv** [oramasearch/orama#501]
I have a usecase where I need to return all documents if the search query is empty, currently I am doing it like this:

```ts
 await search(searchDb, {
	properties: ['nameKebab'],
	limit: entries.length,
	term: '',
})
```

`entries.length` here is the amount of documents I am adding, as the adding is occurring on the lines above.

I am wondering if there is a better way to do this, or if in fact this is the correct way

**Comment by micheleriva** [comment]
Hi @ghostdevv 
you could also proceed as follows:

```js
import { search, count } from '@orama/orama' 

 await search(searchDb, {
	properties: ['nameKebab'],
	limit: await count(searchDb), // Docs: https://docs.oramasearch.com/usage/utilities#count
	term: '',
})
```

But since a lot of people are asking how to return all the docs, maybe it's time for us to implement a dedicated API for that (cc. @allevo).

In the meantime, I'll close this as answered, but feel free to reopen this issue if you need more help. Thanks!

**Comment by ghostdevv** [comment]
Thanks!
